import { ROUTES } from "./routes";

export type PageSeo = {
  title: string;
  description: string;
  path: string;
};

/** Every indexable page's search title and description, in one place */
export const PAGE_SEO = {
  home: {
    title: "Sam-Olayemi | Brand Strategy, Communications & Software Engineering",
    description:
      "Sam-Olayemi builds brands, shapes communication and engineers digital products. Brand strategy, marketing, content, software and web development in one team.",
    path: ROUTES.home,
  },
  services: {
    title: "Services: Brand, Marketing, Communications & Software | Sam-Olayemi",
    description:
      "Brand strategy, marketing, strategic communications, content, ghostwriting, software engineering, web development and consulting from one multidisciplinary team.",
    path: ROUTES.services,
  },
  work: {
    title: "Work & Capabilities | Sam-Olayemi",
    description:
      "How Sam-Olayemi runs brand, campaign, communication, website and software engagements, from strategy through to launch.",
    path: ROUTES.work,
  },
  about: {
    title: "About Sam-Olayemi | Strategy × Creativity × Technology",
    description:
      "Sam-Olayemi is a multidisciplinary company working at the intersection of strategy, creativity, communication and technology.",
    path: ROUTES.about,
  },
  insights: {
    title: "Insights on Brand, Marketing & Technology | Sam-Olayemi",
    description:
      "Articles from Sam-Olayemi on branding, marketing, communication, strategy, software engineering and AI, written for business leaders.",
    path: ROUTES.insights,
  },
  contact: {
    title: "Start a Project | Contact Sam-Olayemi",
    description:
      "Tell Sam-Olayemi what you're working on. Start a project inquiry for branding, marketing, content, software, websites, consulting or training.",
    path: ROUTES.contact,
  },
  privacy: {
    title: "Privacy Policy | Sam-Olayemi",
    description: "How Sam-Olayemi collects, uses and protects the information you share through this website.",
    path: ROUTES.privacy,
  },
  terms: {
    title: "Terms of Use | Sam-Olayemi",
    description: "The terms that apply when you use the Sam-Olayemi website.",
    path: ROUTES.terms,
  },
} as const satisfies Record<string, PageSeo>;

export type PageSeoKey = keyof typeof PAGE_SEO;

/** Generated by app/opengraph-image.tsx */
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "Sam-Olayemi: Strategy × Creativity × Technology",
} as const;
